[package]
name = "rusty-chess"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
bincode = "1.3"

# =======================
# Rusty Chess Executables
# =======================

[[bin]]
name = "terminal-gui"
path = "src/bin/terminal_gui.rs"

[[bin]]
name = "uci"
path = "src/bin/uci.rs"

[[bin]]
name = "best-move"
path = "src/bin/best_move.rs"

[[bin]]
name = "create-opening-book"
path = "src/bin/opening_book.rs"

# ======================
# Rusty Chess Benchmarks
# ======================

[[bin]]
name = "profile"
path = "benches/profile.rs"
